//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sayac_Proje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_SayacEntities2 : DbContext
    {
        public Db_SayacEntities2()
            : base("name=Db_SayacEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_YakitKasasi> Tbl_YakitKasasi { get; set; }
        public virtual DbSet<Tbl_MarketKasasi> Tbl_MarketKasasi { get; set; }
        public virtual DbSet<Tbl_YikamaKasasi> Tbl_YikamaKasasi { get; set; }
    }
}
