//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sayac_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_YikamaKasasi
    {
        public int id { get; set; }
        public Nullable<double> kart { get; set; }
        public Nullable<double> nakit { get; set; }
        public Nullable<double> veresiye { get; set; }
        public Nullable<double> kasaTeslim { get; set; }
        public Nullable<double> gider { get; set; }
        public Nullable<double> toplam { get; set; }
        public string giderFisNo { get; set; }
        public string giderAciklama { get; set; }
        public Nullable<double> tahsilat { get; set; }
        public string tahsilatFisNo { get; set; }
        public string tahsilatAciklama { get; set; }
        public string Aciklama { get; set; }
        public string yikamaci { get; set; }
        public string muhasebeci { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
