//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sayac_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_YakitKasasi
    {
        public int id { get; set; }
        public string pompaci { get; set; }
        public string muhasebeci { get; set; }
        public Nullable<double> zRaporu { get; set; }
        public Nullable<double> otomasyon { get; set; }
        public Nullable<double> halkPos1 { get; set; }
        public Nullable<double> halkPos2 { get; set; }
        public Nullable<double> ziraatPos1 { get; set; }
        public Nullable<double> ziraatPos2 { get; set; }
        public Nullable<double> kart { get; set; }
        public Nullable<double> nakit { get; set; }
        public Nullable<double> veresiye { get; set; }
        public Nullable<double> pompacidanAlinan { get; set; }
        public Nullable<double> gider { get; set; }
        public string fisNo { get; set; }
        public string giderAciklama { get; set; }
        public Nullable<double> toplam { get; set; }
        public Nullable<double> acik { get; set; }
        public Nullable<double> fazla { get; set; }
        public Nullable<double> tahsilat { get; set; }
        public string tahsilatAciklama { get; set; }
        public Nullable<double> benzin { get; set; }
        public Nullable<double> motorin { get; set; }
        public Nullable<double> lpg { get; set; }
        public Nullable<double> yakitLitre { get; set; }
        public Nullable<double> yakitTutar { get; set; }
        public Nullable<double> benzinStok { get; set; }
        public Nullable<double> motorinStok { get; set; }
        public Nullable<double> lpgStok { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<double> gelir { get; set; }
        public string gelirFisNo { get; set; }
        public string gelirAciklama { get; set; }
        public string tahsilatFisNo { get; set; }
    }
}
