//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sayac_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sayac
    {
        public int SAYACID { get; set; }
        public Nullable<int> URUN { get; set; }
        public Nullable<short> POMPA { get; set; }
        public Nullable<decimal> BRMFIYATI { get; set; }
        public Nullable<int> ACILIS { get; set; }
        public Nullable<int> KAPANIS { get; set; }
        public Nullable<int> SATILANLITRE { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
