//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sayac_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MarketKasasi
    {
        public int id { get; set; }
        public Nullable<double> zRaporu { get; set; }
        public Nullable<double> otomasyonToplam { get; set; }
        public Nullable<double> gunSonu1 { get; set; }
        public Nullable<double> gunSonu2 { get; set; }
        public Nullable<double> kartToplam { get; set; }
        public Nullable<double> nakit { get; set; }
        public Nullable<double> veresiyeToplam { get; set; }
        public Nullable<double> muhasebeTeslim { get; set; }
        public Nullable<double> gider { get; set; }
        public string gelirFisNo { get; set; }
        public string giderAciklama { get; set; }
        public Nullable<double> gelir { get; set; }
        public string giderFisNo { get; set; }
        public string gelirAciklama { get; set; }
        public Nullable<double> toplam { get; set; }
        public Nullable<double> acik { get; set; }
        public Nullable<double> fazla { get; set; }
        public Nullable<double> tahsilat { get; set; }
        public string tahsilatFisNo { get; set; }
        public string tahsilatAciklama { get; set; }
        public string kasiyer { get; set; }
        public string muhasebeci { get; set; }
        public string vardiyaNotu { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
